name: CUCM Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  automate-cucm:
    runs-on: self-hosted


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.yml add_userCSV.yml
